name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4.1.7
      
    - name: Set up cache for Cargo dependencies
      uses: actions/cache@v4.0.2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1.0.6

    - name: Install Cargo Dependencies
      run: cargo fetch

    - name: Build with cargo-dist
      run: cargo dist build
      env:
        RUSTFLAGS: "-D warnings"

    - name: Archive release binaries
      if: success()
      run: tar -czf binaries.tar.gz -C dist .
      
    - name: Upload Release Binaries
      uses: actions/upload-artifact@v4.3.6
      with:
        name: binaries
        path: binaries.tar.gz
        
    - name: Clean up
      if: always()
      run: rm -rf dist binaries.tar.gz
